name: CI

on:
  workflow_run:
    workflows: ["Pythonflask app"]
    types:
      - completed

jobs:
  build-and-push-docker:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master  # Specify the branch where your Docker files are

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and tag Docker image
        id: build
        run: |
          docker build -t flask-app-demo:latest .
          echo "::set-output name=tag::latest"
        shell: bash

      - name: Push Docker image
        if: ${{ job.status == 'success' }}
        run: |
          docker tag flask-app-demo:${{ steps.build.outputs.tag }} flask-app-demo:latest
          docker push flask-app-demo:latest
        shell: bash
         

